[package]
edition = "2021"
name = "paw"
version = "0.1.0"

[dependencies]
egui = {version = "^0.23.0", optional = true}
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
micromath = "2.1.0"
num = {version = "0.4.3", default-features = false}
num-derive = "0.4.2"
num-traits = {version = "0.2.19", default-features = false}
static_assertions = "1.1.0"

[features]
egui = ["dep:egui"]
std = []

[dev-dependencies]
criterion = "0.5.1"
nannou = "0.19.0"
nannou_audio = "0.19.0"
nannou_egui = "0.19.0"
plotters = "0.3.7"

[[bench]]
harness = false
name = "wt"

# [[bench]]
# harness = false
# name = "common"
