[package]
name = "paw"
version = "0.1.0"
edition = "2021"

[dependencies]
az = "1.2.1"
egui = { version = "^0.23.0", optional = true }
# az = "1.2.1"
fixed = { version = "1.28.0" }
fugit = "0.3.7"
nannou_egui = "0.19.0"
num = { version = "0.4.3", default-features = false }
num-derive = "0.4.2"
num-traits = { version = "0.2.19", default-features = false }
rodio = { version = "0.20.1", optional = true }
static_assertions = "1.1.0"

[features]
std = []
rodio = ["dep:rodio"]
egui = ["dep:egui"]

[dev-dependencies]
nannou = "0.19.0"
nannou_audio = "0.19.0"
